---
- name: Install Citus PostgreSQL package
  ansible.builtin.package:
    name: "postgresql-{{ pgsql_release }}-citus-{{ citus_release }}"
    state: present
  register: install_citus_apt
  until: install_citus_apt is success
  delay: 5
  retries: 12
  tags:
    - role_install
  notify:
    - Enable postgresql service
    - Start postgresql service

- name: Install wheel
  ansible.builtin.pip:
    name: wheel
    state: present
  tags:
    - role_install

- name: Install postgresql required pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql_pip_packages }}"
  tags:
    - role_install