---
- name: Install Citus PostgreSQL package
  package:
    name: "postgresql-{{ pgsql_release }}-citus-{{ citus_release }}"
    state: present
  become: yes
  register: install_citus_apt
  until: install_citus_apt is success
  delay: 5
  retries: 12
  tags:
    - role_install
  notify:
    - Enable postgresql service
    - Start postgresql service