---
- name: Install apt packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  register: install_apt_packages
  until: install_apt_packages is success
  delay: 5
  retries: 12
  with_items: "{{ packages }}"
  tags:
    - role_install

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  register: install_apt_keys
  until: install_apt_keys is success
  delay: 5
  retries: 12
  with_items: "{{ apt_keys }}"
  tags:
    - role_install

- name: Install apt repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  register: install_apt_repos
  until: install_apt_repos is success
  delay: 5
  retries: 12
  with_items: "{{ apt_repos }}"
  tags:
    - role_install

- name: Ensure a locale exists
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ lc_messages }}"
    - "{{ lc_monetary }}"
    - "{{ lc_numeric }}"
    - "{{ lc_time }}"
  tags:
    - role_install