---
- name: Install apt packages
  package:
    name: "{{ item }}"
    state: present
  become: yes
  register: install_apt_packages
  until: install_apt_packages is success
  delay: 5
  retries: 12
  with_items: "{{ debian_apt_packages }}"
  tags:
    - role_install

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  become: yes
  register: install_apt_keys
  until: install_apt_keys is success
  delay: 5
  retries: 12
  with_items: "{{ debian_apt_keys }}"
  tags:
    - role_install

- name: Install apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  become: yes
  register: install_apt_repos
  until: install_apt_repos is success
  delay: 5
  retries: 12
  with_items: "{{ debian_apt_repos }}"
  tags:
    - role_install