---
- name: Load a variable file based on the OS type
  ansible.builtin.include_vars: 
    file: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}.yml"
    - default.yml
  tags:
    - install
    - configure
    - users
    - databases

- name: Get coordinator node host
  ansible.builtin.set_fact:
    coordinator_host: "{{ (coordinator_dns is defined) | ternary(coordinator_dns, hostvars[groups[citus_coordinator_group][0]].ansible_all_ipv4_addresses | ipaddr('private') | first ) }}"
  tags:
    - install
    - configure
    - users
    - databases

- name: Include OS specific tasks
  include_tasks: "install/{{ ansible_os_family }}.yml"
  tags:
    - install

- name: Include Tuning tasks
  include_tasks: "configure/tuning.yml"
  tags:
    - install
    - configure

- name: Include PostgreSQL Configuration tasks
  include_tasks: "configure/postgresql.yml"
  tags:
    - install
    - configure

- name: Include PostgreSQL Databases tasks
  include_tasks: "configure/databases.yml"
  tags:
    - install
    - configure
    - databases

- name: Include PostgreSQL Users tasks
  include_tasks: "configure/users.yml"
  tags:
    - install
    - configure
    - users