---
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable postgresql service
  ansible.builtin.systemd:
    name: postgresql.service
    enabled: yes

- name: Start postgresql service
  ansible.builtin.systemd:
    name: postgresql.service
    state: started

- name: Stop postgresql service
  ansible.builtin.systemd:
    name: postgresql.service
    state: stopped

- name: Restart postgresql service
  ansible.builtin.systemd:
    name: postgresql.service
    state: restarted