---
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable postgresql service
  ansible.builtin.systemd:
    name: "{{ pgsql_systemd_service }}"
    enabled: yes

- name: Start postgresql service
  ansible.builtin.systemd:
    name: "{{ pgsql_systemd_service }}"
    state: started

- name: Stop postgresql service
  ansible.builtin.systemd:
    name: "{{ pgsql_systemd_service }}"
    state: stopped

- name: Restart postgresql service
  ansible.builtin.systemd:
    name: "{{ pgsql_systemd_service }}"
    state: restarted

- name: Enable disable-thp service
  ansible.builtin.systemd:
    name: "disable-thp.service"
    enabled: yes

- name: Start disable-thp service
  ansible.builtin.systemd:
    name: "disable-thp.service"
    state: started