---
- name: Create postgresql.conf file
  ansible.builtin.template:
    src: "postgresql.conf.j2"
    dest: "{{ pgsql_config_file }}"
    owner: postgres
    group: postgres
    mode: 0644
  become: true
  tags:
    - role_install
    - role_configure

- name: Create postgresql.conf.d files
  ansible.builtin.template:
    src: "postgresql.conf.d/{{ item }}.j2"
    dest: "{{ pgsql_config_directory }}/conf.d/{{ item }}"
    owner: postgres
    group: postgres
    mode: 0644
  become: true
  with_items:
    - "autovacuum.conf"
    - "client_connection_defaults.conf"
    - "connections_authentication.conf"
    - "customized_options.conf"
    - "error_handling.conf"
    - "files_locations.conf"
    - "lock_management.conf"
    - "process_title.conf"
    - "query_tuning.conf"
    - "replication.conf"
    - "reporting_logging.conf"
    - "resource_usage.conf"
    - "statistics.conf"
    - "version_platform_compatibility.conf"
    - "wal.conf"
  tags:
    - role_install
    - role_configure

- name: Create pg_hba.conf file
  ansible.builtin.template:
    src: "pg_hba.conf.j2"
    dest: "{{ hba_file }}"
    owner: postgres
    group: postgres
    mode: 0644
  become: true
  tags:
    - role_install
    - role_configure

- name: Flush handlers to create PostgreSQL Objects
  ansible.builtin.meta: flush_handlers

- name: Alter postgres password
  community.postgresql.postgresql_query:
    query: "ALTER ROLE postgres WITH PASSWORD '{{ postgres_password }}';"
    db: postgres
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default('postgres') }}"
    login_unix_socket: "{{ unix_socket_directories }}"
    port: "{{ item.port | default(omit) }}"
  with_items: "{{ databases }}"
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  when: postgres_password is defined